# Generated by Django 5.2.5 on 2025-10-04 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('acc_type', models.CharField(max_length=10)),
                ('type_of_contact', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('alt_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('taxable', models.BooleanField(blank=True, default=False, null=True)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='nos', max_length=10, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_preference', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobslug', models.CharField(max_length=50)),
                ('jobno', models.CharField(max_length=10, unique=True)),
                ('job_date', models.DateField(blank=True, null=True)),
                ('cust_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('grandtotal', models.FloatField()),
                ('advance', models.FloatField(default=0.0)),
                ('unreg_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('unreg_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.SmallIntegerField()),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.jobcard')),
            ],
        ),
    ]
