# Generated by Django 5.2.5 on 2025-10-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='cust_uuid',
            new_name='cust_id',
        ),
    ]
