# Generated by Django 5.2.5 on 2025-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cust_uuid_jobcard_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='job_status',
            field=models.CharField(default='CONFIRMED', max_length=20),
            preserve_default=False,
        ),
    ]
